INSERT INTO menu (id, text, iconCls, className, menu_id)
VALUES (1, 'menu1', 'fa fa-group fa-lg', NULL, NULL),
       (2, 'menu11', 'xf0c0', 'panel', 1),
       (3, 'menu12', 'xf007', 'panel', 1),
       (4, 'staticData', 'fa fa-database fa-lg', NULL, NULL),
       (5, 'actors', 'xf005', 'panel', 4),
       (6, 'categories', 'xf013', 'panel', 4),
       (7, 'languages', 'xf1ab', 'panel', 4),
       (8, 'cities', 'xf018', 'panel', 4),
       (9, 'countries', 'xf0ac', 'panel', 4),
       (10, 'cms', 'fa fa-film fa-lg', NULL, NULL),
       (11, 'films', 'xf1c8', 'panel', 10),
       (12, 'reports', 'fa fa-line-chart fa-lg', NULL, NULL),
       (13, 'salesfilmcategory', 'xf200', 'panel', 12);
INSERT INTO permissions (menu_id, group_id)
VALUES (1, 1),
       (2, 1),
       (3, 1),
       (4, 1),
       (5, 1),
       (6, 1),
       (7, 1),
       (8, 1),
       (9, 1),
       (10, 1),
       (11, 1),
       (12, 1),
       (13, 1);